# Generated by Django 6.0 on 2025-12-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('nam_sinh', models.IntegerField()),
                ('so_cccd', models.CharField(max_length=20)),
                ('anh_cccd_mat_truoc', models.ImageField(upload_to='cccd/')),
                ('anh_cccd_mat_sau', models.ImageField(upload_to='cccd/')),
                ('anh_bang_cap', models.ImageField(upload_to='bang_cap/')),
                ('ky_nang', models.TextField()),
                ('kinh_nghiem', models.TextField()),
                ('gia_theo_gio', models.IntegerField()),
                ('khu_vuc', models.CharField(max_length=255)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phu_huynh', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField()),
                ('ghi_chu', models.TextField(blank=True)),
                ('trang_thai', models.CharField(default='cho_xac_nhan', max_length=20)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('nguoi_ho_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carepartner')),
            ],
        ),
    ]
