# Generated by Django 6.0 on 2025-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carepartner',
            name='anh_bang_cap',
            field=models.ImageField(blank=True, null=True, upload_to='bang_cap/'),
        ),
        migrations.AlterField(
            model_name='carepartner',
            name='anh_cccd_mat_sau',
            field=models.ImageField(blank=True, null=True, upload_to='cccd/'),
        ),
        migrations.AlterField(
            model_name='carepartner',
            name='anh_cccd_mat_truoc',
            field=models.ImageField(blank=True, null=True, upload_to='cccd/'),
        ),
    ]
