# Generated by Django 6.0 on 2025-12-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carepartner_anh_bang_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carepartner',
            name='dang_hoat_dong',
            field=models.BooleanField(default=True),
        ),
    ]
